{
 "title": "Estación Meteorológica",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperatura Exterior",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "exterior_temp" }
   ]
  },
  {
   "title": "Temperatura Exterior",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "exterior_temp", "legendFormat": "Temperatura Exterior:" }
   ]
  },
  {
   "title": "Temperatura Interior",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "interior_temp", "legendFormat": "Temperatura Interior:" }
   ]
  },
  {
   "title": "Temperatura Interior",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "interior_temp" }
   ]
  },
  {
   "title": "Humedad Exterior",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "exterior_hum", "legendFormat": "Humedad Exterior:" }
   ]
  },
  {
   "title": "Humedad Interior",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "interior_hum", "legendFormat": "Humedad Interior:" }
   ]
  },
  {
   "title": "Humedad Exterior",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "exterior_hum" }
   ]
  },
  {
   "title": "Velocidad Viento",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    { "expr": "velocidad", "legendFormat": "Velocidad Viento:" }
   ]
  },
  {
   "title": "Humedad Interior",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "interior_hum" }
   ]
  }
 ]
}